import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const CATALOG = [
  {
    "slug": "fac_acolhimento",
    "title": "Acolhimento psicológico",
    "origin_type": "institution",
    "category": "Saúde emocional",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "heart",
    "description": "Escuta inicial e acolhedora para momentos difíceis, dúvidas ou sofrimento emocional.",
    "details": "Um primeiro espaço de conversa para compreender o momento vivido e orientar os próximos passos dentro da instituição.",
    "how_to": "Solicitação pelo portal ou pelo setor responsável. A equipe realiza uma escuta inicial e combina o encaminhamento adequado.",
    "when_to": "Quando você sente que precisa conversar, organizar o que está vivendo ou compreender quais apoios podem ajudar.",
    "provider": "Equipe de acolhimento da faculdade",
    "cta_label": "Solicitar acolhimento",
    "featured": true,
    "sort_order": 0
  },
  {
    "slug": "fac_psicoped",
    "title": "Núcleo psicopedagógico",
    "origin_type": "institution",
    "category": "Vida acadêmica",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "puzzle",
    "description": "Apoio para aprendizagem, organização, adaptação acadêmica e desenvolvimento de estratégias de estudo.",
    "details": "Atendimento voltado à forma como o estudante aprende, planeja e enfrenta dificuldades acadêmicas.",
    "how_to": "Após a solicitação, o núcleo avalia a demanda e pode propor encontros individuais, oficinas ou encaminhamentos.",
    "when_to": "Quando há dificuldade de concentração, planejamento, leitura, escrita, rotina ou adaptação às exigências do curso.",
    "provider": "Núcleo de apoio psicopedagógico",
    "cta_label": "Solicitar apoio",
    "featured": true,
    "sort_order": 10
  },
  {
    "slug": "fac_tutoria",
    "title": "Tutoria acadêmica",
    "origin_type": "institution",
    "category": "Vida acadêmica",
    "format": "Mentoria",
    "access_type": "Agendamento",
    "icon": "graduation",
    "description": "Tire dúvidas, revise conteúdos e encontre caminhos para fortalecer sua aprendizagem.",
    "details": "A tutoria aproxima o estudante de monitores, docentes ou colegas preparados para apoiar conteúdos e rotinas acadêmicas.",
    "how_to": "Escolha a disciplina ou tema e consulte horários, turmas ou tutores disponíveis.",
    "when_to": "Quando você precisa rever conteúdos, recuperar lacunas ou se preparar para avaliações e atividades práticas.",
    "provider": "Programa de tutoria da faculdade",
    "cta_label": "Ver tutores",
    "featured": true,
    "sort_order": 20
  },
  {
    "slug": "fac_coordenacao",
    "title": "Orientação com a coordenação",
    "origin_type": "institution",
    "category": "Vida acadêmica",
    "format": "Orientação",
    "access_type": "Agendamento",
    "icon": "building",
    "description": "Converse sobre matrícula, disciplinas, prazos, carga acadêmica e possibilidades de organização do curso.",
    "details": "Canal para esclarecer regras e construir alternativas acadêmicas possíveis dentro do curso.",
    "how_to": "Selecione o curso e envie um breve resumo do tema para facilitar a preparação do atendimento.",
    "when_to": "Quando você precisa tomar decisões sobre disciplinas, faltas, estágio, TCC, mudança de turno ou continuidade.",
    "provider": "Coordenação de curso",
    "cta_label": "Falar com a coordenação",
    "featured": false,
    "sort_order": 30
  },
  {
    "slug": "fac_social",
    "title": "Serviço Social",
    "origin_type": "institution",
    "category": "Apoio material",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "hands",
    "description": "Orientação sobre condições materiais, direitos, auxílios e recursos disponíveis para permanência estudantil.",
    "details": "Acolhe demandas sociais e ajuda a compreender programas, critérios, documentos e alternativas de apoio.",
    "how_to": "A equipe realiza uma escuta social e orienta sobre serviços internos, públicos ou comunitários aplicáveis.",
    "when_to": "Quando renda, moradia, alimentação, transporte, trabalho ou responsabilidades familiares afetam os estudos.",
    "provider": "Assistência estudantil / Serviço Social",
    "cta_label": "Solicitar orientação",
    "featured": false,
    "sort_order": 40
  },
  {
    "slug": "fac_financeiro",
    "title": "Apoio financeiro e bolsas",
    "origin_type": "institution",
    "category": "Apoio material",
    "format": "Orientação",
    "access_type": "Consultar instituição",
    "icon": "wallet",
    "description": "Informações sobre bolsas, descontos, auxílios e programas que podem apoiar sua permanência.",
    "details": "Reúne oportunidades financeiras configuradas pela instituição e orientações para cada processo.",
    "how_to": "Consulte critérios, prazos e documentos. Apenas oportunidades confirmadas pela faculdade aparecem nesta página.",
    "when_to": "Quando despesas ou mudanças de renda dificultam sua continuidade acadêmica.",
    "provider": "Setor financeiro e assistência estudantil",
    "cta_label": "Consultar oportunidades",
    "featured": true,
    "sort_order": 50
  },
  {
    "slug": "fac_alimentacao",
    "title": "Auxílio para alimentação",
    "origin_type": "institution",
    "category": "Apoio material",
    "format": "Orientação",
    "access_type": "Consultar instituição",
    "icon": "food",
    "description": "Conheça programas, benefícios ou orientações relacionados à alimentação estudantil.",
    "details": "Esta área apresenta somente opções cadastradas e confirmadas pela instituição.",
    "how_to": "Verifique os critérios e o canal indicado para cada benefício ou serviço.",
    "when_to": "Quando a alimentação adequada está comprometida ou pesa sobre o orçamento estudantil.",
    "provider": "Assistência estudantil",
    "cta_label": "Ver opções",
    "featured": false,
    "sort_order": 60
  },
  {
    "slug": "fac_transporte",
    "title": "Auxílio para transporte e deslocamento",
    "origin_type": "institution",
    "category": "Apoio material",
    "format": "Orientação",
    "access_type": "Consultar instituição",
    "icon": "bus",
    "description": "Informações sobre auxílios, rotas, benefícios ou alternativas de deslocamento disponíveis.",
    "details": "Facilita o acesso a recursos institucionais relacionados ao deslocamento até o campus.",
    "how_to": "Consulte as alternativas cadastradas e os critérios definidos pela instituição.",
    "when_to": "Quando distância, custo ou tempo de deslocamento afetam frequência e participação.",
    "provider": "Assistência estudantil",
    "cta_label": "Consultar apoio",
    "featured": false,
    "sort_order": 70
  },
  {
    "slug": "fac_acessibilidade",
    "title": "Acessibilidade e inclusão",
    "origin_type": "institution",
    "category": "Acessibilidade",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "accessibility",
    "description": "Recursos e orientações para participação plena em aulas, avaliações, estágios e vida no campus.",
    "details": "Apoio a estudantes com deficiência, neurodivergência, condições de saúde ou necessidades específicas.",
    "how_to": "O núcleo acolhe a solicitação, compreende barreiras e articula adaptações possíveis com os setores responsáveis.",
    "when_to": "Quando alguma barreira física, comunicacional, pedagógica ou atitudinal limita sua participação.",
    "provider": "Núcleo de acessibilidade",
    "cta_label": "Solicitar apoio",
    "featured": true,
    "sort_order": 80
  },
  {
    "slug": "fac_carreira",
    "title": "Orientação de carreira, estágio e emprego",
    "origin_type": "institution",
    "category": "Carreira",
    "format": "Orientação",
    "access_type": "Agendamento",
    "icon": "briefcase",
    "description": "Orientação sobre estágio, currículo, processos seletivos, escolhas profissionais e entrada no mercado.",
    "details": "Apoia decisões de carreira e aproxima o estudante de oportunidades, eventos e ferramentas de empregabilidade.",
    "how_to": "Escolha o tema principal para receber materiais, agenda de encontros ou atendimento individual.",
    "when_to": "Quando você está em dúvida sobre o futuro, busca estágio ou quer se preparar para oportunidades.",
    "provider": "Núcleo de carreiras",
    "cta_label": "Explorar carreira",
    "featured": true,
    "sort_order": 90
  },
  {
    "slug": "fac_monitoria",
    "title": "Monitoria e reforço acadêmico",
    "origin_type": "institution",
    "category": "Vida acadêmica",
    "format": "Grupo",
    "access_type": "Consultar instituição",
    "icon": "book",
    "description": "Encontros para revisar conteúdos, tirar dúvidas e fortalecer bases importantes do curso.",
    "details": "A monitoria complementa as aulas e aproxima estudantes de monitores que já cursaram as disciplinas.",
    "how_to": "Consulte disciplinas, monitores e horários cadastrados pela instituição.",
    "when_to": "Quando uma disciplina ou conteúdo específico está dificultando seu progresso.",
    "provider": "Programa de monitoria",
    "cta_label": "Ver monitorias",
    "featured": false,
    "sort_order": 100
  },
  {
    "slug": "fac_parentalidade",
    "title": "Orientação sobre parentalidade e estudos",
    "origin_type": "institution",
    "category": "Parentalidade",
    "format": "Orientação",
    "access_type": "Agendamento",
    "icon": "family",
    "description": "Apoio para compreender possibilidades acadêmicas diante de gestação e responsabilidades de cuidado.",
    "details": "Conversa sobre rotina, faltas, prazos, carga acadêmica, direitos e recursos que estejam efetivamente disponíveis.",
    "how_to": "O estudante apresenta sua necessidade e recebe orientação dos setores apropriados, sem promessa de serviços não cadastrados.",
    "when_to": "Quando a parentalidade ou o cuidado de crianças afeta frequência, rotina, desempenho ou permanência.",
    "provider": "Coordenação e assistência estudantil",
    "cta_label": "Conversar sobre possibilidades",
    "featured": true,
    "sort_order": 110
  },
  {
    "slug": "fac_pertencimento",
    "title": "Grupos e rodas de conversa",
    "origin_type": "institution",
    "category": "Pertencimento",
    "format": "Grupo",
    "access_type": "Consultar instituição",
    "icon": "users",
    "description": "Espaços de escuta, convivência e troca entre estudantes sobre diferentes experiências universitárias.",
    "details": "Atividades coletivas voltadas a pertencimento, vínculos, inclusão e apoio entre pares.",
    "how_to": "Escolha um tema e consulte os encontros disponíveis no calendário institucional.",
    "when_to": "Quando você busca conexão, troca, acolhimento e participação na comunidade universitária.",
    "provider": "Faculdade",
    "cta_label": "Ver grupos",
    "featured": false,
    "sort_order": 120
  },
  {
    "slug": "fac_ouvidoria",
    "title": "Ouvidoria e canais de proteção",
    "origin_type": "institution",
    "category": "Acessibilidade",
    "format": "Orientação",
    "access_type": "Acesso direto",
    "icon": "shield",
    "description": "Canais para registrar situações de discriminação, violência, assédio, conflito ou violação de direitos.",
    "details": "Apresenta os canais oficiais e explica como cada demanda é recebida e encaminhada.",
    "how_to": "Escolha o canal indicado e consulte orientações de segurança, privacidade e acompanhamento.",
    "when_to": "Quando você vivencia ou presencia uma situação que precisa ser registrada e apurada.",
    "provider": "Ouvidoria institucional",
    "cta_label": "Conhecer canais",
    "featured": false,
    "sort_order": 130
  },
  {
    "slug": "fac_atividade",
    "title": "Esporte, cultura e convivência",
    "origin_type": "institution",
    "category": "Pertencimento",
    "format": "Grupo",
    "access_type": "Consultar instituição",
    "icon": "sparkles",
    "description": "Atividades que favorecem vínculos, expressão, movimento e participação na vida universitária.",
    "details": "Reúne ações culturais, esportivas, artísticas e de convivência cadastradas pela instituição.",
    "how_to": "Consulte agenda, vagas e formas de participação.",
    "when_to": "Quando você busca novas conexões, uma pausa saudável ou maior integração com o campus.",
    "provider": "Faculdade",
    "cta_label": "Ver atividades",
    "featured": false,
    "sort_order": 140
  },
  {
    "slug": "pla_praticas",
    "title": "Práticas guiadas de autorregulação",
    "origin_type": "platform",
    "category": "Práticas e conteúdos",
    "format": "Prática",
    "access_type": "Acesso imediato",
    "icon": "leaf",
    "description": "Exercícios de respiração, grounding, pausas e autorregulação para diferentes momentos do dia.",
    "details": "Práticas curtas e guiadas, com orientações claras e opção de registrar como você estava antes e depois.",
    "how_to": "Escolha uma prática pelo tempo disponível ou pelo que está sentindo e siga o passo a passo.",
    "when_to": "Quando você precisa desacelerar, recuperar foco, reduzir tensão ou atravessar um momento difícil.",
    "provider": "Rede Bem-Estar",
    "cta_label": "Começar uma prática",
    "featured": true,
    "sort_order": 150,
    "cta_route": "/praticas"
  },
  {
    "slug": "pla_psicoterapia",
    "title": "Psicoterapia online",
    "origin_type": "platform",
    "category": "Saúde emocional",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "chat",
    "description": "Atendimento online, sigiloso e acolhedor com psicólogos parceiros da Rede Bem-Estar.",
    "details": "Espaço profissional para conversar sobre emoções, relações, estudos, rotina e outros aspectos da vida.",
    "how_to": "Consulte horários, conheça o profissional e solicite o agendamento dentro do fluxo da plataforma.",
    "when_to": "Quando você deseja acompanhamento psicológico, aprofundar questões ou receber apoio continuado.",
    "provider": "Rede Bem-Estar • profissionais parceiros",
    "cta_label": "Ver horários",
    "featured": true,
    "sort_order": 160,
    "cta_route": "/professionals"
  },
  {
    "slug": "pla_psiquiatria",
    "title": "Consulta psiquiátrica online",
    "origin_type": "platform",
    "category": "Saúde emocional",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "medical",
    "description": "Avaliação psiquiátrica com profissionais parceiros, quando houver indicação e interesse do estudante.",
    "details": "Consulta médica voltada à compreensão do quadro, histórico, funcionamento e possibilidades de cuidado.",
    "how_to": "O estudante consulta disponibilidade e agenda com um profissional parceiro pela plataforma.",
    "when_to": "Quando há necessidade de avaliação médica em saúde mental ou encaminhamento recebido de outro profissional.",
    "provider": "Rede Bem-Estar • profissionais parceiros",
    "cta_label": "Consultar atendimento",
    "featured": false,
    "sort_order": 170,
    "cta_route": "/professionals"
  },
  {
    "slug": "pla_psicoped",
    "title": "Apoio psicopedagógico online",
    "origin_type": "platform",
    "category": "Vida acadêmica",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "puzzle",
    "description": "Atendimento com profissionais parceiros para aprendizagem, rotina, organização e estratégias acadêmicas.",
    "details": "Apoio individualizado para compreender dificuldades e construir recursos mais compatíveis com o estudante.",
    "how_to": "Selecione o tema principal e consulte profissionais e horários disponíveis.",
    "when_to": "Quando dificuldades acadêmicas persistem e você deseja um acompanhamento mais individualizado.",
    "provider": "Rede Bem-Estar • profissionais parceiros",
    "cta_label": "Encontrar profissional",
    "featured": true,
    "sort_order": 180,
    "cta_route": "/professionals"
  },
  {
    "slug": "pla_conteudos",
    "title": "Conteúdos e guias",
    "origin_type": "platform",
    "category": "Práticas e conteúdos",
    "format": "Conteúdo",
    "access_type": "Acesso imediato",
    "icon": "book",
    "description": "Artigos, guias e materiais sobre saúde emocional, estudos, relações, carreira e vida universitária.",
    "details": "Conteúdos curados para transformar informação em orientação prática e acessível.",
    "how_to": "Explore por tema, tempo de leitura ou momento vivido e salve o que for útil.",
    "when_to": "Quando você quer compreender melhor um tema ou encontrar estratégias para o cotidiano.",
    "provider": "Rede Bem-Estar",
    "cta_label": "Explorar conteúdos",
    "featured": false,
    "sort_order": 190,
    "cta_route": "/blog"
  },
  {
    "slug": "pla_grupos",
    "title": "Grupos temáticos online",
    "origin_type": "platform",
    "category": "Pertencimento",
    "format": "Grupo",
    "access_type": "Agendamento",
    "icon": "users",
    "description": "Encontros mediados sobre temas relevantes para estudantes, com troca, acolhimento e aprendizado coletivo.",
    "details": "Grupos organizados por tema e conduzidos por profissionais ou facilitadores parceiros.",
    "how_to": "Consulte temas, datas, regras de participação e vagas disponíveis.",
    "when_to": "Quando você busca identificação, apoio entre pares e conversa orientada sobre uma experiência comum.",
    "provider": "Rede Bem-Estar • rede parceira",
    "cta_label": "Ver grupos",
    "featured": false,
    "sort_order": 200,
    "cta_route": "/encontros"
  },
  {
    "slug": "pla_mentoria_academica",
    "title": "Mentoria acadêmica",
    "origin_type": "platform",
    "category": "Vida acadêmica",
    "format": "Mentoria",
    "access_type": "Agendamento",
    "icon": "graduation",
    "description": "Apoio para organização, decisões acadêmicas, rotina e desenvolvimento ao longo do curso.",
    "details": "Conversa estruturada com mentores para transformar dificuldades e objetivos em passos concretos.",
    "how_to": "Escolha o foco da mentoria e consulte profissionais ou mentores disponíveis.",
    "when_to": "Quando você quer desenvolver autonomia, organização e direção na trajetória acadêmica.",
    "provider": "Rede Bem-Estar • mentores parceiros",
    "cta_label": "Encontrar mentoria",
    "featured": false,
    "sort_order": 210
  },
  {
    "slug": "pla_mentoria_carreira",
    "title": "Mentoria de carreira",
    "origin_type": "platform",
    "category": "Carreira",
    "format": "Mentoria",
    "access_type": "Agendamento",
    "icon": "briefcase",
    "description": "Converse sobre caminhos profissionais, decisões, competências, estágio e posicionamento no mercado.",
    "details": "Mentoria para estudantes que desejam explorar possibilidades e organizar um plano de desenvolvimento.",
    "how_to": "Selecione o objetivo principal e consulte mentores com experiências compatíveis.",
    "when_to": "Quando você está em dúvida sobre o futuro ou quer se preparar para oportunidades.",
    "provider": "Rede Bem-Estar • mentores parceiros",
    "cta_label": "Explorar mentores",
    "featured": true,
    "sort_order": 220
  },
  {
    "slug": "pla_financeira",
    "title": "Orientação financeira para estudantes",
    "origin_type": "platform",
    "category": "Apoio material",
    "format": "Mentoria",
    "access_type": "Agendamento",
    "icon": "wallet",
    "description": "Apoio para orçamento, prioridades, organização financeira e decisões compatíveis com a vida universitária.",
    "details": "Orientação educativa, sem substituir aconselhamento financeiro regulado quando necessário.",
    "how_to": "Mapeie o tema principal e agende uma conversa com mentor parceiro.",
    "when_to": "Quando dinheiro, dívidas ou falta de organização aumentam o estresse e afetam os estudos.",
    "provider": "Rede Bem-Estar • mentores parceiros",
    "cta_label": "Agendar orientação",
    "featured": false,
    "sort_order": 230,
    "cta_route": "/professionals"
  },
  {
    "slug": "pla_parentalidade",
    "title": "Trilha parentalidade e estudos",
    "origin_type": "platform",
    "category": "Parentalidade",
    "format": "Trilha",
    "access_type": "Acesso imediato",
    "icon": "family",
    "description": "Conteúdos e estratégias para conciliar responsabilidades de cuidado, rotina e permanência acadêmica.",
    "details": "Uma jornada voltada a mães, pais, gestantes, responsáveis e cuidadores que estudam.",
    "how_to": "Explore temas como rotina, rede de apoio, comunicação com a instituição, autocuidado e organização acadêmica.",
    "when_to": "Quando a parentalidade ou o cuidado de crianças exige reorganização da vida universitária.",
    "provider": "Rede Bem-Estar",
    "cta_label": "Começar trilha",
    "featured": true,
    "sort_order": 240,
    "cta_route": "/praticas"
  },
  {
    "slug": "pla_mindfulness",
    "title": "Meditação e mindfulness",
    "origin_type": "platform",
    "category": "Práticas e conteúdos",
    "format": "Prática",
    "access_type": "Acesso imediato",
    "icon": "lotus",
    "description": "Áudios e práticas para atenção, presença, relaxamento e equilíbrio no dia a dia.",
    "details": "Sessões curtas com diferentes durações e objetivos, para usar de forma autônoma.",
    "how_to": "Escolha uma prática pela duração ou pelo seu estado atual e siga as orientações.",
    "when_to": "Quando você quer reduzir agitação, pausar ou treinar atenção e presença.",
    "provider": "Rede Bem-Estar • curadoria parceira",
    "cta_label": "Escolher prática",
    "featured": false,
    "sort_order": 250
  },
  {
    "slug": "pla_sono",
    "title": "Sono e recuperação",
    "origin_type": "platform",
    "category": "Práticas e conteúdos",
    "format": "Trilha",
    "access_type": "Acesso imediato",
    "icon": "moon",
    "description": "Conteúdos e práticas para compreender hábitos de sono e construir uma rotina de recuperação mais saudável.",
    "details": "Jornada educativa com exercícios de rotina, relaxamento e acompanhamento pessoal.",
    "how_to": "Faça um diagnóstico leve de hábitos e escolha pequenos passos para testar.",
    "when_to": "Quando sono insuficiente, horários irregulares ou cansaço afetam seu funcionamento.",
    "provider": "Rede Bem-Estar",
    "cta_label": "Explorar trilha",
    "featured": false,
    "sort_order": 260,
    "cta_route": "/praticas"
  },
  {
    "slug": "pla_tcc",
    "title": "Organização para TCC e projetos longos",
    "origin_type": "platform",
    "category": "Vida acadêmica",
    "format": "Trilha",
    "access_type": "Acesso imediato",
    "icon": "book",
    "description": "Uma jornada prática para transformar projetos extensos em etapas menores, possíveis e acompanháveis.",
    "details": "Inclui planejamento, definição de prioridades, sessões de foco e revisão de progresso.",
    "how_to": "Informe seu prazo e etapa atual para receber uma sequência sugerida de ações.",
    "when_to": "Quando TCC, pesquisa ou projeto extenso está gerando bloqueio, atraso ou sobrecarga.",
    "provider": "Rede Bem-Estar",
    "cta_label": "Montar plano",
    "featured": false,
    "sort_order": 270,
    "cta_route": "/praticas"
  },
  {
    "slug": "pla_nutricao",
    "title": "Orientação nutricional parceira",
    "origin_type": "platform",
    "category": "Saúde emocional",
    "format": "Atendimento individual",
    "access_type": "Agendamento",
    "icon": "food",
    "description": "Atendimento com nutricionistas parceiros para apoiar alimentação, rotina e saúde durante a vida universitária.",
    "details": "Orientação profissional individualizada, integrada à realidade e aos objetivos do estudante.",
    "how_to": "Consulte disponibilidade e agende com profissional parceiro pela plataforma.",
    "when_to": "Quando alimentação, energia, rotina ou relação com a comida precisam de atenção profissional.",
    "provider": "Rede Bem-Estar • profissionais parceiros",
    "cta_label": "Encontrar profissional",
    "featured": false,
    "sort_order": 280,
    "cta_route": "/professionals"
  }
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
  const { error } = await supabase
    .from("support_catalog")
    .upsert(CATALOG, { onConflict: "slug" });
  if (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
  return new Response(JSON.stringify({ seeded: CATALOG.length }), {
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
});
