import "https://deno.land/x/xhr@0.1.0/mod.ts"
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Process base64 in chunks to prevent memory issues
function processBase64Chunks(base64String: string, chunkSize = 32768) {
  const chunks: Uint8Array[] = [];
  let position = 0;
  
  while (position < base64String.length) {
    const chunk = base64String.slice(position, position + chunkSize);
    const binaryChunk = atob(chunk);
    const bytes = new Uint8Array(binaryChunk.length);
    
    for (let i = 0; i < binaryChunk.length; i++) {
      bytes[i] = binaryChunk.charCodeAt(i);
    }
    
    chunks.push(bytes);
    position += chunkSize;
  }

  const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;

  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }

  return result;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { audio } = await req.json()
    
    if (!audio) {
      throw new Error('No audio data provided')
    }

    console.log('Starting transcription with Alô, Psi...')

    // Process audio in chunks
    const binaryAudio = processBase64Chunks(audio)
    
    // Prepare form data
    const formData = new FormData()
    const blob = new Blob([binaryAudio], { type: 'audio/webm' })
    formData.append('file', blob, 'audio.webm')
    formData.append('model', 'whisper-1')
    formData.append('language', 'pt')

    // Send to OpenAI
    const response = await fetch('https://api.openai.com/v1/audio/transcriptions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
      },
      body: formData,
    })

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${await response.text()}`)
    }

    const result = await response.json()
    console.log('Transcription completed:', result.text)

    // Process the transcription with Alô, Psi to create a reflection
    const reflectionResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: `Você é Alô, Psi - um assistente de inteligência artificial especializado em saúde mental e bem-estar emocional. 

Sua tarefa é analisar a transcrição de um áudio gravado por um usuário em seu diário emocional e criar uma reflexão organizada e empática.

Diretrizes:
- Mantenha um tom acolhedor e empático
- Organize os pensamentos de forma clara
- Identifique emoções principais mencionadas
- Destaque insights importantes
- Use linguagem natural e acessível
- Mantenha o conteúdo original do usuário, apenas organizando melhor
- Se o áudio for muito curto ou pouco claro, crie uma reflexão baseada no que foi possível entender

Formato de resposta: Escreva uma reflexão em primeira pessoa como se fosse o próprio usuário, mas de forma mais organizada e reflexiva.`
          },
          {
            role: 'user',
            content: `Por favor, analise esta transcrição de áudio e crie uma reflexão organizada para o diário emocional:

"${result.text}"`
          }
        ],
        temperature: 0.7,
        max_tokens: 500
      }),
    })

    if (!reflectionResponse.ok) {
      throw new Error(`OpenAI reflection error: ${await reflectionResponse.text()}`)
    }

    const reflectionResult = await reflectionResponse.json()
    const reflection = reflectionResult.choices[0].message.content

    console.log('Reflection generated by Alô, Psi')

    return new Response(
      JSON.stringify({ 
        transcription: result.text,
        reflection: reflection
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Transcription error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )
  }
})