// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getTenantSlugFromPath, buildTenantPath } from '@/utils/tenantHelpers';

const SUPABASE_URL = "https://mbuljmpamdocnxppueww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idWxqbXBhbWRvY254cHB1ZXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTMxNzUsImV4cCI6MjA3MTU4OTE3NX0.byP_5kv4bwOSpenNl0giMneBNv7396XjWkFMOwc_ttY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Listener global para erros de autenticação
supabase.auth.onAuthStateChange((event, session) => {
  // ✅ Apenas operações síncronas
  if (event === 'SIGNED_OUT') {
    console.log('🔒 [Supabase Client] User signed out - clearing session');
    localStorage.clear();
    sessionStorage.clear();
    
    if (typeof window !== 'undefined') {
      // Detectar tenant atual e redirecionar para homepage correta
      const tenantSlug = getTenantSlugFromPath(window.location.pathname);
      const homePath = buildTenantPath(tenantSlug, '/');
      
      // Só redireciona se não estiver na homepage já
      if (window.location.pathname !== homePath) {
        window.location.href = homePath;
      }
    }
  }
});